---
linters-settings:
  lll:
    line-length: 140
    tab-width: 4

  unused:
    check-exported: true

  unparam:
    algo: rta
    check-exported: true

linters:
  enable-all: true
  disable:
    - scopelint         # too many false positives
    - gochecknoglobals  # mostly useless

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
